# Project information
site_name: Nijmegen Roleplay wet en regelgeving
site_url: "https://gittafivem.github.io/"
site_description: "Wet en regelgeving van Nijmegen Roleplay roleplay"
site_author: "Nijmegen Roleplay"

# Copyright
copyright: Copyright &copy; 2019 - 2022 Nijmegen Roleplay

# Repository
repo_url: "https://github.com/Gittafivem/nijmegen-wetboek"
repo_name: "Gittafivem/nijmegen-wetboek"
edit_uri: "edit/pre-release/docs/"

google_analytics: ["UA-167800475-3", "gittafivem.github.io"]

# Congiguration
theme:
  name: material
  #   features:
  #     - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  favicon: img/logo.png
  logo: img/logo.png
  custom_dir: docs/overrides
  language: nl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - toc.follow
    - content.action.edit
    - content.action.view
  extra:
    analytics:
      provider: google
      property: UA-167800475-3

plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
